version: '3.7'

services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    working_dir: /var/www
    volumes:
      - './web:/var/www'
    environment:
      - DB_HOST=mysqldb #same name as service below
      - DB_PORT=3306

  #web (nginx)
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    working_dir: /var/www
    volumes:
    - ./web:/var/www
    depends_on:
      - web
    ports: 
      - "8181:80"

  #MYSQL DB
  mysqldb:
    image: mysql:5.7
    volumes:
      - slimdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=app" #named whatever the project is
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=rootpassword"
    ports:
      - "33062:3306"

#select volumes to use
volumes:
  slimdata: