FROM php:7.3-fpm

RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    unzip \
    zlib1g-dev \
    libzip-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libxml2-dev \
    inkscape \
    libmagickwand-dev --no-install-recommends \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd \
    && docker-php-ext-configure soap --enable-soap \
    && docker-php-ext-configure pdo_mysql --with-pdo-mysql \
    && docker-php-ext-configure mbstring --enable-mbstring \
    && docker-php-ext-configure opcache --enable-opcache \
    && docker-php-ext-install zip pdo pdo_mysql opcache \
    dom   \
    iconv \
    gd \
    mbstring \
    soap \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug

COPY . /var/www
#COPY ./config/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

# Change website folder rights and upload your website
RUN chown -R www-data:www-data /var/www


WORKDIR /var/www

# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/bin

# get install script and pass it to execute: 
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash
# and install node 
RUN apt-get install nodejs